[package]
name = "RustProject"
version = "0.1.0"
authors = ["icecream777 <hgk.1998@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.7.3"
indexmap = "1.4.0"
mint = "0.5.5"
